version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.16.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Build
          command: npm run build

  deploy_firebase:
    docker:
      - image: cimg/node:18.16.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # Add any other cache keys relevant to your project

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
            # Add any other cache keys relevant to your project

      - run:
          name: Build
          command: npm run build

      - run:
          name: Firebase Deploy
          command: |
            sudo npm install -g firebase-tools@12.4.7
            echo $FIREBASE_SERVICE_ACCOUNT
            # echo $FIREBASE_SERVICE_ACCOUNT > firebase-key.json
            firebase deploy --only hosting:react-todo-circleci --token "$FIREBASE_SERVICE_ACCOUNT" --project fir-intro-4b6a4 --token "$FIREBASE_SERVICE_ACCOUNT"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy_firebase:
          requires:
            - build
