version: 2.1
jobs:     
  build:
    docker:
      - image: cimg/node:18.16.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Build
          command: npm run build

      - run:
          name: Unit Test
          command: npm run test

  deploy_firebase:
    docker:
      - image: cimg/node:18.16.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Build
          command: npm run build

      - run:
          name: Firebase Deploy
          command: |
            sudo npm install -g firebase-tools@12.4.7
            firebase deploy --only hosting:react-todo-circleci --token=$FIREBASE_TOKEN
            
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - deploy_firebase:
          requires:
            - unit_test
